# Generated by Django 5.1.7 on 2025-03-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
            ],
            options={
                'db_table': 'taskdata',
            },
        ),
    ]
